#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Oct 24 13:29:07 2025
#

import wx
from wxglade_out  import ventana4
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade



class ventana3(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0):
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        # begin wxGlade: ventana3.__init__
        self.SetSize((830, 741))
        self.SetTitle("frame_2")
        print(f"Datos de la ventana 2:\n Información: {informacion} \n")
        print(f"subtotal: {subtotal}")


        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(56, 147, 160))
        self.panel_1.SetForegroundColour(wx.Colour(255, 0, 0))
        
        self.infoDulceria = ""
        self.subtotalDulceria=0
        self.infoTaquilla=informacion
        self.subtotalTaquilla=subtotal

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(6, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenlogo2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_1, 0, 0, 0)

        lbDulceia = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERIA")
        lbDulceia.SetFont(wx.Font(18, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_2.Add(lbDulceia, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenlogo2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_2, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_3.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_8.Add(sizer_3, 1, wx.EXPAND, 0)

        self.spComboB = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_3.Add(self.spComboB, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(3, 1, 0, 0)
        sizer_3.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        lbBasico = wx.StaticText(self.panel_1, wx.ID_ANY, u"BÁSICO $75")
        lbBasico.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_10.Add(lbBasico, 0, 0, 0)

        lbPalomitas = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas ch")
        lbPalomitas.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_10.Add(lbPalomitas, 0, 0, 0)

        lbRefresco = wx.StaticText(self.panel_1, wx.ID_ANY, "Refresco ch")
        lbRefresco.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_10.Add(lbRefresco, 0, 0, 0)

        grid_sizer_18 = wx.GridSizer(1, 2, 0, 0)
        sizer_3.Add(grid_sizer_18, 1, wx.EXPAND, 0)

        bitmap_5 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenpalo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_18.Add(bitmap_5, 0, 0, 0)

        bitmap_6 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenunres4.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_18.Add(bitmap_6, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3.Add(sizer_2, 1, wx.EXPAND, 0)

        self.spComboC = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_2.Add(self.spComboC, 0, 0, 0)

        grid_sizer_9 = wx.GridSizer(2, 1, 0, 0)
        sizer_2.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        lbCuates = wx.StaticText(self.panel_1, wx.ID_ANY, "Cuates $130")
        lbCuates.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_9.Add(lbCuates, 0, 0, 0)

        lbplomitas = wx.StaticText(self.panel_1, wx.ID_ANY, "plomitas Md\n")
        lbplomitas.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_9.Add(lbplomitas, 0, 0, 0)

        grid_sizer_19 = wx.GridSizer(1, 2, 0, 0)
        sizer_2.Add(grid_sizer_19, 1, wx.EXPAND, 0)

        bitmap_7 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenpalo.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_19.Add(bitmap_7, 0, 0, 0)

        bitmap_8 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenunres4.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_19.Add(bitmap_8, 0, 0, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_4.Add(sizer_4, 1, wx.EXPAND, 0)

        self.spComboF = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        sizer_4.Add(self.spComboF, 0, 0, 0)

        grid_sizer_11 = wx.GridSizer(2, 1, 0, 0)
        sizer_4.Add(grid_sizer_11, 1, wx.EXPAND, 0)

        lbFamiliar = wx.StaticText(self.panel_1, wx.ID_ANY, "FAMILIAR $200")
        lbFamiliar.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_11.Add(lbFamiliar, 0, 0, 0)

        lbPalomitasG = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitas G")
        lbPalomitasG.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_11.Add(lbPalomitasG, 0, 0, 0)

        bitmap_9 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenpalo.png", wx.BITMAP_TYPE_ANY))
        sizer_4.Add(bitmap_9, 0, 0, 0)

        grid_sizer_4.Add((0, 0), 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_5.Add(sizer_5, 1, wx.EXPAND, 0)

        bitmap_11 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenpalo.png", wx.BITMAP_TYPE_ANY))
        sizer_5.Add(bitmap_11, 0, 0, 0)

        grid_sizer_12 = wx.GridSizer(2, 1, 0, 0)
        sizer_5.Add(grid_sizer_12, 1, wx.EXPAND, 0)

        lbPalomitass = wx.StaticText(self.panel_1, wx.ID_ANY, "Palomitass")
        lbPalomitass.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_12.Add(lbPalomitass, 0, 0, 0)

        grid_sizer_16 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_12.Add(grid_sizer_16, 1, wx.EXPAND, 0)

        grid_sizer_17 = wx.FlexGridSizer(1, 6, 0, 0)
        grid_sizer_16.Add(grid_sizer_17, 1, wx.EXPAND, 0)

        self.spPalomitasCh = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_17.Add(self.spPalomitasCh, 0, 0, 0)

        lbChicas = wx.StaticText(self.panel_1, wx.ID_ANY, "Chicas")
        lbChicas.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_17.Add(lbChicas, 0, 0, 0)

        self.spPalomitasMd = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_17.Add(self.spPalomitasMd, 0, 0, 0)

        lbMedianas = wx.StaticText(self.panel_1, wx.ID_ANY, "Medianas")
        lbMedianas.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_17.Add(lbMedianas, 0, 0, 0)

        self.spPalomitasG = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_17.Add(self.spPalomitasG, 0, 0, 0)

        lbGrandes = wx.StaticText(self.panel_1, wx.ID_ANY, "Grandes")
        lbGrandes.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_17.Add(lbGrandes, 0, 0, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_5.Add(sizer_6, 1, wx.EXPAND, 0)

        bitmap_10 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/imagenres3.png", wx.BITMAP_TYPE_ANY))
        sizer_6.Add(bitmap_10, 0, 0, 0)

        grid_sizer_13 = wx.GridSizer(3, 1, 0, 0)
        sizer_6.Add(grid_sizer_13, 1, wx.EXPAND, 0)

        lbResfrescos = wx.StaticText(self.panel_1, wx.ID_ANY, "Refrescos")
        lbResfrescos.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_13.Add(lbResfrescos, 0, 0, 0)

        lbTamano = wx.StaticText(self.panel_1, wx.ID_ANY, u"Tamaño")
        lbTamano.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_13.Add(lbTamano, 0, 0, 0)

        self.cmbTamano = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["CHICO","MEDIANO","GRANDE"], style=wx.CB_DROPDOWN)
        grid_sizer_13.Add(self.cmbTamano, 0, wx.ALL, 0)

        grid_sizer_14 = wx.GridSizer(2, 1, 0, 0)
        sizer_6.Add(grid_sizer_14, 1, wx.EXPAND, 0)

        lbSabor = wx.StaticText(self.panel_1, wx.ID_ANY, "Sabor")
        lbSabor.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_14.Add(lbSabor, 0, 0, 0)

        self.cmbSabor = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["COCA COLA","RED COLA","MANZANITA"], style=wx.CB_DROPDOWN)
        grid_sizer_14.Add(self.cmbSabor, 0, wx.ALIGN_CENTER | wx.ALL, 0)

        grid_sizer_15 = wx.GridSizer(3, 1, 0, 0)
        sizer_6.Add(grid_sizer_15, 1, wx.EXPAND, 0)

        lbCantidad = wx.StaticText(self.panel_1, wx.ID_ANY, "Cantidad")
        lbCantidad.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_15.Add(lbCantidad, 0, 0, 0)

        self.spCantidad = wx.SpinCtrl(self.panel_1, wx.ID_ANY, "0", min=0, max=100)
        grid_sizer_15.Add(self.spCantidad, 0, 0, 0)

        self.btnAgregar = wx.Button(self.panel_1, wx.ID_ANY, "Agregar\n")
        grid_sizer_15.Add(self.btnAgregar, 0, 0, 0)

        grid_sizer_6 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_6, 1, wx.EXPAND, 0)

        self.lbProductosAgregados = wx.StaticText(self.panel_1, wx.ID_ANY, "Productos Agregados:..")
        self.lbProductosAgregados.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_6.Add(self.lbProductosAgregados, 0, 0, 0)

        self.lbSubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, u"Subtotal Dulcería:")
        self.lbSubtotal.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_6.Add(self.lbSubtotal, 0, 0, 0)

        grid_sizer_7 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_1.Add(grid_sizer_7, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n\n")
        self.btnLimpiar.SetMinSize((95, 57))
        self.btnLimpiar.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_7.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        self.btnSiguiente.SetMinSize((95, 57))
        self.btnSiguiente.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Stencil"))
        grid_sizer_7.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.spComboB.Bind(wx.EVT_SPINCTRL, self.calcularComboBasico)
        self.spComboC.Bind(wx.EVT_SPINCTRL, self.calcularComboCuates)
        self.spComboF.Bind(wx.EVT_SPINCTRL, self.calcularComboFamiliar)
        self.spPalomitasCh.Bind(wx.EVT_SPINCTRL, self.calcularComboCh)
        self.spPalomitasMd.Bind(wx.EVT_SPINCTRL, self.calcularComboMd)
        self.spPalomitasG.Bind(wx.EVT_SPINCTRL, self.calcularComboG)
        self.btnAgregar.Bind(wx.EVT_BUTTON, self.agregarrefresco)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarDulceria)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteDulceria)
        # end wxGlade

    def calcularComboBasico(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboB.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combos Basicos \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboCuates(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboC.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combo Cuates \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboFamiliar(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spComboF.GetValue())
        subtotalcombo=numero*60
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Combo Familiar \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboCh(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasCh.GetValue())
        subtotalcombo=numero*80
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Ch \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboMd(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasMd.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas Md \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def calcularComboG(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spPalomitasG.GetValue())
        subtotalcombo=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalcombo
        self.lbSubtotal.SetLabel(f"${self.subtotalDulceria}")
        self.infoDulceria=self.infoDulceria + f"{numero} Palomitas G \n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)
        event.Skip()

    def agregarrefresco(self, event):  # wxGlade: ventana3.<event_handler>
        numero=int(self.spCantidad.GetValue())
        tamanyo=self.cmbTamano.GetValue()
        sabor=self.cmbSabor.GetValue()
        if tamanyo == "CHICO":
            subtotalrefresco=numero*25
        elif tamanyo == "MEDIANO":
            subtotalrefresco=numero*40
        elif tamanyo == "GRANDE":
            subtotalrefresco=numero*75
        self.subtotalDulceria=self.subtotalDulceria+subtotalrefresco
        self.lbSubtotal.SetLabel (f"${self.subtotalDulceria}")   

        self.infoDulceria=self.infoDulceria + f"{numero} Refresco: {sabor} tamaño {tamanyo}\n"
        self.lbProductosAgregados.SetLabel(self.infoDulceria)         
        event.Skip()
    def limpiarD(self):
        self.subtotalDulceria=0
        self.infoDulceria=""

        self.spComboB.SetValue(0)
        self.spComboC.SetValue(0)
        self.spComboF.SetValue(0)
        self.spPalomitasCh.SetValue(0)
        self.spPalomitasMd.SetValue(0)
        self.spPalomitasG.SetValue(0)
        self.spCantidad.SetValue(0)
        self.cmbSabor.SetSelection(wx.NOT_FOUND)
        self.cmbTamano.SetSelection(wx.NOT_FOUND)
        self.lbProductosAgregados.SetLabel("---")
        self.lbSubtotal.SetLabel("$00.00")

    def limpiarDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        self.limpiarD()
        event.Skip()

    def siguienteDulceria(self, event):  # wxGlade: ventana3.<event_handler>
        pregunta = wx.MessageDialog(self,
        f"Confirmacion de Dulceria. \n"
        f"¿Estas suguro que desea arquirir?\n\n{self.infoDulceria}\n"
        f"subtotal Dulceria: ${self.subtotalDulceria}",
        "dulceria", style=wx.YES_NO | wx.ICON_QUESTION)

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            v4 = ventana4(self, informacion=self.infoTaquilla, 
                         subtotal=self.subtotalTaquilla,
                         informacion2=self.infoDulceria,
                         subtotal2=self.subtotalDulceria)
            v4.Show()
            self.limpiarD()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD()
        event.Skip()

# end of class ventana3
class ventana2(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana2.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((585, 709))
        self.SetTitle("frame_1")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./imagen1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, 0, 0)

        lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        lbTaquilla.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Snap ITC"))
        grid_sizer_1.Add(lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./imagen1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.ALIGN_RIGHT, 0)

        grid_sizer_4 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        lbPeli = wx.StaticText(self.panel_1, wx.ID_ANY, "pelicula:")
        lbPeli.SetFont(wx.Font(16, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_2.Add(lbPeli, 0, 0, 0)

        self.lbsala = wx.StaticText(self.panel_1, wx.ID_ANY, "Sala:")
        self.lbsala.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_2.Add(self.lbsala, 0, 0, 0)

        lbHorario = wx.StaticText(self.panel_1, wx.ID_ANY, "Horario:")
        lbHorario.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        grid_sizer_2.Add(lbHorario, 0, 0, 0)

        grid_sizer_3 = wx.GridSizer(3, 1, 0, 0)
        grid_sizer_4.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        self.cbmpeli = wx.ComboBox(self.panel_1, wx.ID_ANY, choices=["Rapidos y Furiosos 5", "Lucy", "Interestelar"], style=wx.CB_DROPDOWN)
        self.cbmpeli.SetMinSize((100, 23))
        grid_sizer_3.Add(self.cbmpeli, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSala = wx.StaticText(self.panel_1, wx.ID_ANY, "__")
        grid_sizer_3.Add(self.lbSala, 0, 0, 0)

        grid_sizer_5 = wx.GridSizer(2, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_5, 1, wx.EXPAND, 0)

        self.rbHorario1 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00\n")
        grid_sizer_5.Add(self.rbHorario1, 0, 0, 0)

        self.rbHorario2 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario2, 0, 0, 0)

        self.rbHorario3 = wx.RadioButton(self.panel_1, wx.ID_ANY, "00:00")
        grid_sizer_5.Add(self.rbHorario3, 0, 0, 0)

        grid_sizer_5.Add((0, 0), 0, 0, 0)

        self.bmPelicula = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./imagen2.jpg", wx.BITMAP_TYPE_ANY))
        grid_sizer_4.Add(self.bmPelicula, 0, 0, 0)

        lbBoletos = wx.StaticText(self.panel_1, wx.ID_ANY, "Boletos", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbBoletos.SetMinSize((123, 30))
        lbBoletos.SetFont(wx.Font(14, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Showcard Gothic"))
        sizer_1.Add(lbBoletos, 0, wx.EXPAND, 0)

        grid_sizer_8 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_8, 1, wx.EXPAND, 0)

        lbAdultos = wx.StaticText(self.panel_1, wx.ID_ANY, "Adultos($80):")
        lbAdultos.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        grid_sizer_8.Add(lbAdultos, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.tfAdultos = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        grid_sizer_8.Add(self.tfAdultos, 0, wx.ALIGN_CENTER | wx.ALL, 0)

        grid_sizer_9 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_9, 1, wx.EXPAND, 0)

        lbMenores = wx.StaticText(self.panel_1, wx.ID_ANY, "Menores($70):")
        lbMenores.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Snap ITC"))
        grid_sizer_9.Add(lbMenores, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        self.tfMenores = wx.TextCtrl(self.panel_1, wx.ID_ANY, "",style=wx.TE_PROCESS_ENTER)
        grid_sizer_9.Add(self.tfMenores, 0, wx.ALIGN_CENTER | wx.ALL, 0)

        self.lbsubtotal = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal: $")
        self.lbsubtotal.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Broadway"))
        sizer_1.Add(self.lbsubtotal, 0, 0, 0)

        grid_sizer_10 = wx.GridSizer(1, 2, 0, 0)
        sizer_1.Add(grid_sizer_10, 1, wx.EXPAND, 0)

        self.btnLimpiar = wx.Button(self.panel_1, wx.ID_ANY, "Limpiar\n")
        self.btnLimpiar.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Bernard MT Condensed"))
        grid_sizer_10.Add(self.btnLimpiar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnSiguiente = wx.Button(self.panel_1, wx.ID_ANY, "Siguiente\n")
        self.btnSiguiente.SetFont(wx.Font(11, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        grid_sizer_10.Add(self.btnSiguiente, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.cbmpeli.Bind(wx.EVT_COMBOBOX, self.seleccionPelicula)
        self.rbHorario1.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario1)
        self.rbHorario2.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario2)
        self.rbHorario3.Bind(wx.EVT_RADIOBUTTON, self.seleccionHorario3)
        self.tfAdultos.Bind(wx.EVT_TEXT_ENTER, self.sumarAdultos)
        self.tfMenores.Bind(wx.EVT_TEXT_ENTER, self.sumarMenores)
        self.btnLimpiar.Bind(wx.EVT_BUTTON, self.limpiarTaquilla)
        self.btnSiguiente.Bind(wx.EVT_BUTTON, self.siguienteVentana)
        # end wxGlade

    def cargar_imagen(self,ruta):
        print(f"imagen a cargar {ruta}")
        bitmap = wx.Bitmap(ruta,wx.BITMAP_TYPE_ANY)
        self.bmPelicula.SetBitmap(bitmap)

    def seleccionPelicula(self, event):  # wxGlade: ventana2.<event_handler>
        pelicula=self.cbmpeli.GetValue()
        imagen=""
        sala=""
        horario1=horario2=horario3=""

        print(f"pelicula seleccionada: {pelicula}")

        if pelicula == "Rapidos y Furiosos 5":
            imagen="imagen2.jpg"
            sala="1"
            horario1="14:00"
            horario2="17:00"
            horario3="20:00"

        elif pelicula == "Lucy":
            imagen="lucy.jpg"
            sala="2"
            horario1="13:30"    
            horario2="16:30"
            horario3="19:30"

        elif pelicula =="Interestelar":
            imagen="imagen3.jpg"
            sala="3"
            horario1="15:00"
            horario2="18:00"
            horario3="21:00"

        self.cargar_imagen(imagen)
        self.lbSala.SetLabel(sala)
        self.rbHorario1.SetLabel(horario1)
        self.rbHorario2.SetLabel(horario2)
        self.rbHorario3.SetLabel(horario3)
        self.informacion=f"pelicula: {pelicula}  \n  sala:  {sala}"
        print(f"Listo para disfrutar de \n {self.informacion}")
        event.Skip()

    def seleccionHorario1(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario1.GetLabelText()
        event.Skip()

    def seleccionHorario2(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario2.GetLabelText()
        event.Skip()

    def seleccionHorario3(self, event):  # wxGlade: ventana2.<event_handler>
        self.horarioSeleccionado=self.rbHorario3.GetLabelText()
        event.Skip()

    def sumarAdultos(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.adultos = int(self.tfAdultos.GetValue())
            subtotal_a = self.adultos * 80
            self.subtotal=subtotal_a
            self.lbsubtotal.SetLabel(f"subtotal: ${subtotal_a:.2f}")
        except ValueError:
            wx.MessageBox("por favor ingresa un numero valido", "Error" , wx.OK | wx.ICON_EEROR)    
        event.Skip()

    def sumarMenores(self, event):  # wxGlade: ventana2.<event_handler>
        try:
            self.menores = int(self.tfMenores.GetValue())
            subtotal_b = self.menores * 70
            self.subtotal=(self.adultos*80) + subtotal_b
            self.lbsubtotal.SetLabel(f"Subtotal: ${self.subtotal:.2f}")
        except ValueError:
            wx.MessageBox("por favor ingresa un numero valido", "error", wx.OK  | wx.ICON_ERROR)
        event.Skip()

    def limpiarValores_Campos(self):

        self.subtotal=0
        self.adultos=0
        self.menores=0
        self.informacion=""
        self.horarioSeleccionado=""

        self.cargar_imagen("logo.png")
        self.rbHorario1.SetLabel("00:00")
        self.rbHorario2.SetLabel("00:00")
        self.rbHorario3.SetLabel("00:00")
        self.rbHorario1.SetValue(False)
        self.rbHorario2.SetValue(False)
        self.rbHorario3.SetValue(False)
        self.cbmpeli.SetSelection(wx.NOT_FOUND)
        self.lbSala.SetLabel("---")
        self.tfAdultos.SetValue("0")
        self.tfMenores.SetValue("0")
        self.lbsubtotal.SetLabel("0")

    def limpiarTaquilla(self, event):  # wxGlade: ventana2.<event_handler>
        self.limpiarValores_Campos()
        event.Skip()

    def siguienteVentana(self, event):  # wxGlade: ventana2.<event_handler>
        self.informacion = f"{self.informacion}  \n  Horario: {self.horarioSeleccionado}"
        self.informacion = f"{self.informacion}  \n  Adultos: {self.adultos}\n Menores de 12 años: {self.menores}"
        self.informacion = f"{self.informacion}  \n  subtotal: {self.subtotal}"

        pregunta = wx.MessageDialog(
        self,
        f"confirmacion de taquilla.\n"
        f"¿Esta seguro que desea adquirir?\n\n{self.informacion}"
        "taquilla",
        style=wx.YES_NO | wx.ICON_QUESTION
        )

        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
            print(f"Venta de taquilla realizada\n {self.informacion}")
            v3 = ventana3(self, informacion=self.informacion, subtotal=self.subtotal)
            v3.Show()
            self.limpiarValores_Campos()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarValores_Campos()    

        event.Skip()

# end of class ventana2

class ventana1(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ventana1.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 393))
        self.SetTitle(u"inicio de sesión - Cine plus")
        _icon = wx.NullIcon
        _icon.CopyFromBitmap(wx.Bitmap("C:\\Users\\PC\\Documents\\CinePlusEmilio\\imagen.png", wx.BITMAP_TYPE_ANY))
        self.SetIcon(_icon)

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(219, 112, 147))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        lbBienvenidos = wx.StaticText(self.panel_1, wx.ID_ANY, "bienvenidos a cine plus", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbBienvenidos.SetForegroundColour(wx.Colour(255, 255, 255))
        lbBienvenidos.SetFont(wx.Font(20, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(lbBienvenidos, 0, 0, 0)

        lbLogo = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("./imagen.png", wx.BITMAP_TYPE_ANY))
        sizer_1.Add(lbLogo, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbUsuario = wx.StaticText(self.panel_1, wx.ID_ANY, "Usuario:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbUsuario.SetForegroundColour(wx.Colour(255, 255, 255))
        lbUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(lbUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfUsuario = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.tfUsuario.SetMinSize((200, 27))
        self.tfUsuario.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "AriaI"))
        sizer_1.Add(self.tfUsuario, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        lbClave = wx.StaticText(self.panel_1, wx.ID_ANY, u"Contraseña:", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbClave.SetForegroundColour(wx.Colour(255, 255, 255))
        lbClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(lbClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.tfClave = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.tfClave.SetMinSize((200, 27))
        self.tfClave.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.tfClave, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnEntrar = wx.Button(self.panel_1, wx.ID_ANY, "Entrar")
        self.btnEntrar.SetMinSize((120, 35))
        self.btnEntrar.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(self.btnEntrar, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.btnSalir = wx.Button(self.panel_1, wx.ID_ANY, "salir")
        self.btnSalir.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_NORMAL, 0, "Arial Rounded MT Bold"))
        sizer_1.Add(self.btnSalir, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnEntrar.Bind(wx.EVT_BUTTON, self.confirmar_usuario_clave)
        self.btnSalir.Bind(wx.EVT_BUTTON, self.cerrar_programa)
        # end wxGlade

    def confirmar_usuario_clave(self, event):  # wxGlade: ventana1.<event_handler>
        nombre = self.tfUsuario.GetValue()
        clave = self.tfClave.GetValue()

        if nombre == "emilio" and clave == "777":
         print(f"¡Bienvenido,{nombre}¡Acceso autorizado.")
         E2 = ventana2(self)
         E2.Show()
         self.Hide()
         
        else:
         print("Acceso denegado. Usuario o clave incorrectos.")  
        event.Skip()

    def cerrar_programa(self, event):  # wxGlade: ventana1.<event_handler>
        pregunta = wx.MessageDialog(self,"se cerrara la ventana.\n" \
        "confirmar salida",style=wx.YES_NO | wx.ICON_QUESTION)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()

        if respuesta == wx.ID_YES:
           print("BYE!") 
           self.Close()
        event.Skip()
        if respuesta == wx.ID_YES:
            self.limpiarD()
            self.Hide()
        elif respuesta == wx.ID_NO:
            self.limpiarD()
        event.Skip()
# end of class ventana1

class MyApp(wx.App):
    def OnInit(self):
        self.frame = ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()

class ventana4(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0, informacion2="", subtotal2=0):
        self.SetSize((400, 500))
        self.SetTitle("Ticket - Resumen de Compra")

        # Variables de instancia
        self.infoTaquilla = informacion
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal
        self.subtotalDulceria = subtotal2
        self.total = self.subtotalTaquilla + self.subtotalDulceria

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(255, 143, 176))

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        # TÍTULO TICKET
        grid_sizer_1 = wx.GridSizer(1, 3, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("imagenes/boletov2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_1, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        label_1.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        grid_sizer_1.Add(label_1, 0, wx.ALIGN_CENTER, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("imagenes/boletov2.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_1.Add(bitmap_2, 0, wx.EXPAND, 0)

        # SECCIÓN TAQUILLA
        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_2.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 10)

        self.lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}")
        self.lbTaquilla.SetMinSize((350, 100))
        self.lbTaquilla.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.lbSubtotalTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal Taquilla: ${self.subtotalTaquilla:.2f}")
        self.lbSubtotalTaquilla.SetForegroundColour(wx.Colour(35, 35, 142))
        self.lbSubtotalTaquilla.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotalTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        # SECCIÓN DULCERÍA
        label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, "DULCERÍA")
        label_3.SetFont(wx.Font(14, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(label_3, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP, 10)

        self.lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}")
        self.lbDulceria.SetMinSize((350, 100))
        self.lbDulceria.SetFont(wx.Font(10, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Arial"))
        sizer_1.Add(self.lbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 5)

        self.lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"Subtotal Dulcería: ${self.subtotalDulceria:.2f}")
        self.lbSubtotalDulceria.SetForegroundColour(wx.Colour(35, 35, 142))
        self.lbSubtotalDulceria.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbSubtotalDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.BOTTOM, 10)

        # LÍNEA SEPARADORA
        static_line = wx.StaticLine(self.panel_1, wx.ID_ANY)
        sizer_1.Add(static_line, 0, wx.EXPAND | wx.ALL, 10)

        # TOTAL
        self.lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"TOTAL: ${self.total:.2f}")
        self.lbTotal.SetForegroundColour(wx.Colour(189, 0, 0))
        self.lbTotal.SetFont(wx.Font(16, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        sizer_1.Add(self.lbTotal, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.TOP | wx.BOTTOM, 10)

        # BOTONES
        grid_sizer_2 = wx.GridSizer(1, 2, 20, 20)
        sizer_1.Add(grid_sizer_2, 1, wx.EXPAND | wx.ALL, 20)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar")
        self.btnCancelar.SetMinSize((120, 40))
        self.btnCancelar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_ITALIC, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnCancelar.SetBackgroundColour(wx.Colour(255, 100, 100))
        grid_sizer_2.Add(self.btnCancelar, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        self.btnFinalizar.SetMinSize((120, 40))
        self.btnFinalizar.SetFont(wx.Font(12, wx.FONTFAMILY_SWISS, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, "Arial"))
        self.btnFinalizar.SetBackgroundColour(wx.Colour(100, 255, 100))
        grid_sizer_2.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER | wx.ALL, 4)

        self.panel_1.SetSizer(sizer_1)
        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.finalizarVenta)

    def cancelarVenta(self, event):
        pregunta = wx.MessageDialog(self,
            "¿Está seguro de cancelar esta venta?\n"
            "Todos los datos se perderán.",
            "Cancelar Venta",
            style=wx.YES_NO | wx.ICON_WARNING)
        
        respuesta = pregunta.ShowModal()
        pregunta.Destroy()
        
        if respuesta == wx.ID_YES:
            print("Venta cancelada")
            self.Close()
            
            # Mostrar ventana principal
            app = wx.GetApp()
            if app and hasattr(app, 'frame'):
                app.frame.Show()
        event.Skip()

    def finalizarVenta(self, event):
        mensaje = (
            f"VENTA FINALIZADA\n\n"
            f"Taquilla: ${self.subtotalTaquilla:.2f}\n"
            f"Dulcería: ${self.subtotalDulceria:.2f}\n"
            f"TOTAL: ${self.total:.2f}\n\n"
            f"¡Gracias por su compra!"
        )
        
        wx.MessageBox(mensaje, "Venta Finalizada", wx.OK | wx.ICON_INFORMATION)
        
        print(f"Venta finalizada - Total: ${self.total:.2f}")
        
        # Cerrar esta ventana
        self.Close()
        
        # Mostrar ventana de inicio
        app = wx.GetApp()
        if app and hasattr(app, 'frame'):
            app.frame.Show()
        event.Skip()

class MyAppCinePlus(wx.App):
    def OnInit(self):
        self.frame = Ventana1(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

if __name__ == "__main__":
    appCinePlus = MyAppCinePlus(0)
    appCinePlus.MainLoop()