#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.1 on Fri Dec  5 12:53:43 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ventana4(wx.Frame):
    def __init__(self, parent, informacion="", subtotal=0, informacion2="", subtotal2=0):
        # begin wxGlade: ventana4.__init__
        super().__init__(parent, style= wx.DEFAULT_FRAME_STYLE)
        self.SetSize((400, 628))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)
        self.panel_1.SetBackgroundColour(wx.Colour(159, 159, 95))

        self.infoTaquilla = informacion
        self.infoDulceria = informacion2
        self.subtotalTaquilla = subtotal
        self.subtotalDulceria = subtotal2
        self.total=self.subtotalTaquilla+self.subtotalDulceria

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        grid_sizer_1 = wx.GridSizer(9, 1, 0, 0)
        sizer_1.Add(grid_sizer_1, 1, wx.EXPAND, 0)

        grid_sizer_2 = wx.GridSizer(1, 3, 0, 0)
        grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/CinePlusEmilio/imagen1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_1, 0, wx.ALIGN_CENTER_VERTICAL, 0)

        lb = wx.StaticText(self.panel_1, wx.ID_ANY, "TICKET")
        grid_sizer_2.Add(lb, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        bitmap_2 = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap("E:/cineameDULCERIA/CinePlusEmilio/imagen1.png", wx.BITMAP_TYPE_ANY))
        grid_sizer_2.Add(bitmap_2, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "TAQUILLA")
        label_2.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_1.Add(label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbTaquilla = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoTaquilla}")
        grid_sizer_1.Add(self.lbTaquilla, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotalTaquila = wx.StaticText(self.panel_1, wx.ID_ANY, f"subtotal: $ {self.subtotalTaquilla}")
        self.lbSubtotalTaquila.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_1.Add(self.lbSubtotalTaquila, 0, 0, 0)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY,  f"subtotal: $ {self.subtotalDulceria}")
        label_4.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_1.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, f"{self.infoDulceria}")
        grid_sizer_1.Add(self.lbDulceria, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.lbSubtotalDulceria = wx.StaticText(self.panel_1, wx.ID_ANY, "Subtotal:$")
        self.lbSubtotalDulceria.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_1.Add(self.lbSubtotalDulceria, 0, 0, 0)

        self.lbTotal = wx.StaticText(self.panel_1, wx.ID_ANY, f"total: ${self.total}")
        self.lbTotal.SetFont(wx.Font(12, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Showcard Gothic"))
        grid_sizer_1.Add(self.lbTotal, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT, 0)

        grid_sizer_3 = wx.GridSizer(1, 1, 0, 0)
        grid_sizer_1.Add(grid_sizer_3, 1, wx.EXPAND, 0)

        grid_sizer_4 = wx.GridSizer(1, 2, 0, 0)
        grid_sizer_3.Add(grid_sizer_4, 1, wx.EXPAND, 0)

        self.btnCancelar = wx.Button(self.panel_1, wx.ID_ANY, "Cancelar\n")
        grid_sizer_4.Add(self.btnCancelar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.btnFinalizar = wx.Button(self.panel_1, wx.ID_ANY, "Finalizar")
        grid_sizer_4.Add(self.btnFinalizar, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()

        self.btnCancelar.Bind(wx.EVT_BUTTON, self.cancelarVenta)
        self.btnFinalizar.Bind(wx.EVT_BUTTON, self.FinalizarVenta)
        # end wxGlade

    def cancelarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        wx.Exit()
        event.Skip()

    def FinalizarVenta(self, event):  # wxGlade: ventana4.<event_handler>
        v2 = ventana2(self)
        v2.Show()
        self.Hide()
        event.Skip()

# end of class ventana4

class MyApp(wx.App):
    def OnInit(self):
        self.frame = ventana4(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
